### ISSUE TITLE
upload_assets中response返回异常

### ISSUE THREAD

**Issue by Karmenzind** [nICEnnnnnnnLee/action-gitee-release#4]
```shell
Traceback (most recent call last):
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 204, in <module>
    upload_asset()
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 188, in upload_asset
    result = upload_assets(gitee_files, gitee_client, gitee_repo, gitee_release_id)
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 135, in upload_assets
    success, msg = gitee_client.upload_asset(gitee_repo, gitee_release_id, file_name = os.path.basename(file_path), file_path = file_path)
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 32, in run
    return checkRun(retry, *args, **kwargs)
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 21, in checkRun
    raise e
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 18, in checkRun
    return func(*args, **kwargs)
  File "/home/runner/work/_actions/nicennnnnnnlee/action-gitee-release/v1.0.5/gitee_release.py", line 95, in upload_asset
    res = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line [34](https://github.com/Karmenzind/kd/actions/runs/11425213102/job/31786597182#step:10:36)6, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line [35](https://github.com/Karmenzind/kd/actions/runs/11425213102/job/31786597182#step:10:37)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
```

config:
```yaml
      - name: Test upload file to exist release
        uses: nicennnnnnnlee/action-gitee-release@v1.0.5
        with:
          gitee_owner: void_kmz
          gitee_repo: kd
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          gitee_release_id: "release-beta"
          gitee_upload_retry_times:  3
          gitee_files: |
            build/kd_macos_arm64
            build/kd_macos_amd64

```

**Comment by nICEnnnnnnnLee** [comment]
`gitee_release_id`只能从api中获取，网页扣不到的。
另外。如果是本项目创建的release，你可以通过step result得到。而在action运行完毕后，你也可以通过log观察得到。

**Comment by Karmenzind** [comment]
成功了，感谢。
同名文件似乎可以重复上传，有办法支持一下覆盖同名文件吗？
![image](https://github.com/user-attachments/assets/c26ecba6-9247-4384-a122-ac0a15da8582)

**Comment by nICEnnnnnnnLee** [comment]
没有计划支持
